name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gustavoaraujo-git
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Personalizações adicionais
          color: "#FF6F61"  # Cor da cobrinha (rosa moderno)
          background: "#2D2D2D"  # Cor de fundo (escuro para contraste)
          snake_color: gradient  # Usar gradiente na cobrinha
          snake_speed: fast  # Velocidade da animação (pode ser slow, medium, fast)
          snake_style: rounded  # Estilo da cobrinha (rounded para bordas arredondadas)

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
