name: Generate Datas

on:
  schedule: 
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gustavoaraujo-git
          gif_out_path: dist/github-contribution-grid-snake.gif 
          svg_out_path: dist/github-contribution-grid-snake.svg 
          color: "#FF6F61"  
          background: "#2D2D2D"  
          snake_color: gradient  
          snake_speed: fast  
          snake_style: rounded 

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

